name: Release OpenBD

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-release:
    strategy:
      matrix:
        java: [21]
        os: [ubuntu-latest]
    name: Java Build ${{ matrix.java }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup JDK ${{ matrix.java }} (GraalVM)
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: "graalvm"

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Make Gradle wrappers executable
        run: |
          chmod +x ./gradlew
        shell: bash

      - name: Build
        run: ./gradlew build
        shell: bash

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
            name: OpenBD ${{ github.ref_name }}
            draft: true 
            files: ./build/libs/*